apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-replicaset
  name: mongodb-replicaset-metrics
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: mongodb-replicaset
    release: mongodb-replicaset
  sessionAffinity: None
  type: ClusterIP

